import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/dropzone/styles.css";

import localFont from "next/font/local";

import { ColorSchemeScript } from "@mantine/core";
import Providers from "./components/Global/Provider";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./static/font/PretendardVariable.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "ACG 인트라넷 Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={myFont.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
